name: Docker CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

       #Github actions doesn't have SHORT SHA variable, so I will generate it - https://stackoverflow.com/a/64195658/13954598    
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
        
      - name: Build Docker Image with plugin v8
        run: docker build . -t danpaldev/wp-pluginv8:${SHORT_SHA} --build-arg PLUGIN_VERSION=8
      
      - name: Build Docker Image with plugin v9
        run: docker build . -t danpaldev/wp-pluginv9:${SHORT_SHA} --build-arg PLUGIN_VERSION=9

      - name: Push Docker Image with plugin v8
        run: docker push danpaldev/wp-pluginv8:${SHORT_SHA}

      - name: Push Docker Image with plugin v9
        run: docker push danpaldev/wp-pluginv9:${SHORT_SHA}
